-- Auto-generated by Matugen
-- names match ghostty's palette so the two agree

return {
  bg = '{{colors.background.default.hex}}',
  bg_dim = '{{colors.surface_container_lowest.default.hex}}',
  bg_alt = '{{colors.surface_container_low.default.hex}}',
  bg_light = '{{colors.surface_container.default.hex}}',
  bg_lighter = '{{colors.surface_container_high.default.hex}}',
  bg_highlight = '{{colors.surface_container_highest.default.hex}}',

  fg = '{{colors.on_surface.default.hex}}',
  fg_dim = '{{colors.on_surface_variant.default.hex}}',
  grey = '{{colors.outline.default.hex}}',
  border = '{{colors.outline_variant.default.hex}}',

  red = '{{colors.error.default.hex}}',
  green = '{{colors.primary.default.hex}}',
  yellow = '{{colors.tertiary.default.hex}}',
  blue = '{{colors.secondary.default.hex}}',
  magenta = '{{colors.primary_fixed.default.hex}}',
  cyan = '{{colors.secondary_fixed.default.hex}}',

  accent = '{{colors.primary.default.hex}}',
  on_accent = '{{colors.on_primary.default.hex}}',
  selection = '{{colors.secondary_container.default.hex}}',
  on_selection = '{{colors.on_secondary_container.default.hex}}',

  -- harmonised by matugen, see modules/editors/vim.nix
  rainbow_red = '{{colors.rainbow_red.default.hex}}',
  rainbow_orange = '{{colors.rainbow_orange.default.hex}}',
  rainbow_yellow = '{{colors.rainbow_yellow.default.hex}}',
  rainbow_green = '{{colors.rainbow_green.default.hex}}',
  rainbow_cyan = '{{colors.rainbow_cyan.default.hex}}',
  rainbow_blue = '{{colors.rainbow_blue.default.hex}}',
  rainbow_violet = '{{colors.rainbow_violet.default.hex}}',
}
